# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: でゆき的博客
subtitle: '技术与生活的分享'
description: '一个关于技术、生活和随想的个人博客'
keywords: 技术, 博客, 编程, 生活
author: でゆき
language:
- zh-CN
- zh-TW
- en
- ja
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://deyuki.cn
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# hexo-generator-index-i18n
index_generator:
  per_page: 10
  order_by: -date
  exclude:
    - 'tags/**'
    - 'categories/**'
i18n:
  type: [page, post]
  generator: [index, archive, category, tag]

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# Theme Next Settings
theme_config:
  scheme: Gemini
  menu:
    home: / || fa fa-home
    about: /about/ || fa fa-user
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
  sidebar:
    position: left
  favicon:
    small: /images/favicon-16x16.png
    medium: /images/favicon-32x32.png
    apple_touch_icon: /images/apple-touch-icon.png
    safari_pinned_tab: /images/logo.svg
  
  # Custom styles
  custom_file_path:
    style: source/css/custom.css
    variable: source/_data/styles.styl

  # Custom colors
  custom_colors:
    primary: "#a8d8ff"  # 淡蓝色
    accent: "#ffb6c1"   # 浅粉色

  # Enable custom file injections
  style: source/_data/styles.styl

  footer:
    # Footer powered by
    powered:
      enable: true
      version: true
      text: '<i class="fab fa-hexo"></i>'
      
    # Next theme info
    theme:
      enable: true
      version: true
      text: '<i class="fas fa-gem"></i>'